version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: esm-api

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000

  email-worker:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: esm-email-worker

    restart: unless-stopped

    env_file:
      - .env

    command: python -m app.workers.email_worker