name: ESM Deployment

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update Project
        shell: powershell
        run: |
          Set-Location "E:\Deployment\ESM"

          git fetch origin
          git checkout deployment
          git reset --hard origin/deployment

      - name: Stop Containers
        shell: powershell
        run: |
          Set-Location "E:\Deployment\ESM"

          docker compose down

      - name: Build Docker Images
        shell: powershell
        run: |
          Set-Location "E:\Deployment\ESM"

          docker compose build

      - name: Start Containers
        shell: powershell
        run: |
          Set-Location "E:\Deployment\ESM"

          docker compose up -d

      - name: Verify Containers
        shell: powershell
        run: |
          docker ps